on:
 push:
  branches:
    - 'main'
- name: FTP Deploy Forked
  # You may pin to the exact commit or the version.
  # uses: snorux/FTP-Deploy-Action@34f2dffd579b47565ccbcb90f9aa28b0a3556cf5
  uses: snorux/FTP-Deploy-Action@1.3.2
  with:
    # ftp server
    server: ftpupload.net
    # ftp username
    username: if0_36718460
    # ftp password
    password: 1FJUJ6IlVzZ
    # Server port to connect to (read your web hosts docs)
    port: # optional
    # protocol to deploy with - ftp, ftps, or ftps-legacy
    protocol: # optional
    # Folder to upload from, must end with trailing slash /
    local-dir: # optional
    # Path to upload to on the server. Must end with trailing slash /
    server-dir: # optional
    # Path and name of the state file - this file is used to track which files have been deployed
    state-name: # optional
    # Prints which modifications will be made with current config options, but doesnt actually make any changes
    dry-run: # optional
    # Deletes ALL contents of server-dir, even items in excluded with exclude argument
    dangerous-clean-slate: # optional
    # An array of glob patterns, these files will not be included in the publish/delete process
    exclude: # optional
    # How verbose should the information be - warn, info, debug
    log-level: # optional
    # strict or loose
    security: # optional
    # Number of retries to be made when the connection fails
    max-retries: # optional
          
