on: 
 push:
  branches:
  - main
name: FTP Deploy Forke
jobs:
  web-deploy:
     name: Deploy
     runs-on: ubuntu-latest
     steps:
     - name: Get latest code
       uses: actions/checkout@v2.3.2
       
     - name: Sync files
       uses: Samkirkland/Ftp-Deploy-Action@4.0.0
       with:
         server: ftpupload.net
         username: if0_36718460
         password: 1FJUJ6IlVzZ
         server-dir: /htdocs/
   
